rootProject.name = "kairo"

include(":kairo-clock-feature")
include(":kairo-config")
include(":kairo-darb")
include(":kairo-dependency-injection")
include(":kairo-feature")
include(":kairo-feature:testing")
include(":kairo-health-check-feature")
include(":kairo-id-feature")
include(":kairo-logging")
include(":kairo-logging:testing")
include(":kairo-logging-feature")
include(":kairo-protected-string")
include(":kairo-reflect")
include(":kairo-rest-feature")
include(":kairo-rest-feature:testing")
include(":kairo-serialization")
include(":kairo-server")
include(":kairo-server:testing")
include(":kairo-testing")
include(":kairo-transaction-manager")
include(":kairo-updater")
include(":kairo-util")
