rootProject.name = "kairo"

include(":bom")
include(":bom-full")

include(":kairo-application")
include(":kairo-config")
include(":kairo-coroutines")
include(":kairo-darb")
include(":kairo-dependency-injection")
include(":kairo-dependency-injection:feature")
include(":kairo-exception")
include(":kairo-exception:testing")
include(":kairo-feature")
include(":kairo-feature:testing")
include(":kairo-gcp-secret-supplier")
include(":kairo-gcp-secret-supplier:testing")
include(":kairo-health-check:feature")
include(":kairo-id")
include(":kairo-logging")
include(":kairo-protected-string")
include(":kairo-reflect")
include(":kairo-rest")
include(":kairo-rest:feature")
include(":kairo-server")
include(":kairo-sql")
include(":kairo-sql:feature")
include(":kairo-sql:feature:postgres-testing")
include(":kairo-sql:postgres")
include(":kairo-testing")
include(":kairo-util")
