package com.piperframework.dataConversion.conversionService

import com.piperframework.dataConversion.DataConversionService
import com.piperframework.types.LocalDateTime

expect object LocalDateTimeConversionService : DataConversionService<LocalDateTime>
