CREATE TABLE IF NOT EXISTS library_book (
  id TEXT PRIMARY KEY,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  title TEXT NOT NULL,
  isbn TEXT NOT NULL,
  genre TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq__library_book__isbn ON library_book (isbn);
