dependencies {
  implementation(project(":limber-backend:common:client"))
  api(project(":limber-backend:common:config"))
  api(project(":limber-backend:common:exception-mapping"))
  api(project(":limber-backend:common:module"))
  api(project(":limber-backend:common:reps"))
  api(project(":limber-backend:common:serialization"))
  implementation(project(":limber-backend:common:type-conversion"))
  implementation(Dependencies.Google.guice)
  implementation(Dependencies.Jackson.dataFormatYaml)
  implementation(Dependencies.Jwt.auth0JavaJwt)
  implementation(Dependencies.Jwt.auth0JwksRsa)
  implementation(Dependencies.Ktor.jackson)
  api(Dependencies.Ktor.serverCore)
  implementation(Dependencies.Ktor.serverHostCommon)
}
