set -e

docker build -t limber-monolith:master .

docker run -p 55100:55100 \
  -e LIMBER_CONFIG=prod \
  -e LIMBER_PROD_POSTGRES_JDBC_URL="$LIMBER_PROD_POSTGRES_JDBC_URL" \
  -e LIMBER_PROD_POSTGRES_USERNAME="$LIMBER_PROD_POSTGRES_USERNAME" \
  -e LIMBER_PROD_POSTGRES_PASSWORD="$LIMBER_PROD_POSTGRES_PASSWORD" \
  -e LIMBER_PROD_JWT_SECRET="$LIMBER_PROD_JWT_SECRET" \
  limber-monolith:master
