# When upgrading Detekt versions, review default-detekt-config.yaml as well as the changelog
# and decide which changes to make in this file.

build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: true
  checkExhaustiveness: true

processors:
  active: false
  exclude:
    - 'KtFileCountProcessor'
    - 'PackageCountProcessor'
    - 'ClassCountProcessor'
    - 'FunctionCountProcessor'
    - 'PropertyCountProcessor'
    - 'ProjectComplexityProcessor'
    - 'ProjectCognitiveComplexityProcessor'
    - 'ProjectLLOCProcessor'
    - 'ProjectCLOCProcessor'
    - 'ProjectLOCProcessor'
    - 'ProjectSLOCProcessor'
    - 'LicenseHeaderLoaderExtension'

console-reports:
  active: true
  exclude:
    - 'FileBasedFindingsReport'

output-reports:
  active: false

comments:
  AbsentOrWrongFileLicense:
    active: false
  CommentOverPrivateFunction:
    active: false
  CommentOverPrivateProperty:
    active: false
  DeprecatedBlockTag:
    active: true
  EndOfSentenceFormat:
    active: true
  KDocReferencesNonPublicProperty:
    active: false
  OutdatedDocumentation:
    active: true
    matchTypeParameters: true
    matchDeclarationsOrder: true
    allowParamOnConstructorProperties: false
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false
  UndocumentedPublicProperty:
    active: false

complexity:
  CognitiveComplexMethod:
    active: true # Unsure how this differs from CyclomaticComplexMethod and if one is preferable.
    threshold: 12
  ComplexCondition:
    active: true
    threshold: 3
  ComplexInterface:
    active: true
    threshold: 8
    includeStaticDeclarations: true
    includePrivateDeclarations: false
    ignoreOverloaded: false
  CyclomaticComplexMethod: # Unsure how this differs from CognitiveComplexMethod and if one is preferable.
    active: true
    threshold: 12
    ignoreSingleWhenExpression: true
    ignoreSimpleWhenEntries: true
    ignoreNestingFunctions: false
  LabeledExpression:
    active: false
  LargeClass:
    active: false # Good practice, but leave this up to the developer.
  LongMethod:
    active: true
    threshold: 40
  LongParameterList:
    active: true
    functionThreshold: 4
    constructorThreshold: 4
    ignoreDefaultParameters: false
    ignoreDataClasses: true
    ignoreAnnotated:
      - 'com.google.inject.Inject'
  MethodOverloading:
    active: false
  NamedArguments:
    active: false # Good practice, but leave this up to the developer.
  NestedBlockDepth:
    active: true
    threshold: 4
  NestedScopeFunctions:
    active: true
    threshold: 3
  ReplaceSafeCallChainWithRun:
    active: true
  StringLiteralDuplication:
    active: false # Could consider enabling this.
  TooManyFunctions:
    active: false # Good practice, but leave this up to the developer.

coroutines:
  GlobalCoroutineUsage:
    active: true
  InjectDispatcher:
    active: false
  RedundantSuspendModifier:
    active: true
  SleepInsteadOfDelay:
    active: true
  SuspendFunSwallowedCancellation:
    active: true
  SuspendFunWithCoroutineScopeReceiver:
    active: true
  SuspendFunWithFlowReturnType:
    active: true

empty-blocks:
  EmptyCatchBlock:
    active: true
  EmptyClassBlock:
    active: true
  EmptyDefaultConstructor:
    active: true
  EmptyDoWhileBlock:
    active: true
  EmptyElseBlock:
    active: true
  EmptyFinallyBlock:
    active: true
  EmptyForBlock:
    active: true
  EmptyFunctionBlock:
    active: true
    ignoreOverridden: false
  EmptyIfBlock:
    active: true
  EmptyInitBlock:
    active: true
  EmptyKtFile:
    active: true
  EmptySecondaryConstructor:
    active: true
  EmptyTryBlock:
    active: true
  EmptyWhenBlock:
    active: true
  EmptyWhileBlock:
    active: true

exceptions:
  ExceptionRaisedInUnexpectedLocation:
    active: true
  InstanceOfCheckForException:
    active: true
  NotImplementedDeclaration:
    active: false
  ObjectExtendsThrowable:
    active: true
  PrintStackTrace:
    active: true
  RethrowCaughtException:
    active: true
  ReturnFromFinally:
    active: true
    ignoreLabeled: false
  SwallowedException:
    active: true
  ThrowingExceptionFromFinally:
    active: true
  ThrowingExceptionInMain:
    active: true
  ThrowingExceptionsWithoutMessageOrCause:
    active: true
  ThrowingNewInstanceOfSameException:
    active: true
  TooGenericExceptionCaught:
    active: false # This is a pretty common and useful thing to do!
  TooGenericExceptionThrown:
    active: true

formatting:
  AnnotationOnSeparateLine:
    active: false
  AnnotationSpacing:
    active: true
    autoCorrect: true
  ArgumentListWrapping:
    active: true
    autoCorrect: true
    indentSize: 2
    maxLineLength: 120
  BlockCommentInitialStarAlignment:
    active: true
    autoCorrect: true
  ChainWrapping:
    active: true
    autoCorrect: true
    indentSize: 2
  ClassName:
    active: true
  CommentSpacing:
    active: true
    autoCorrect: true
  CommentWrapping:
    active: true
    autoCorrect: true
    indentSize: 2
  ContextReceiverMapping:
    active: true
    maxLineLength: 120
    indentSize: 2
  DiscouragedCommentLocation:
    active: true
  EnumEntryNameCase:
    active: false # Overlaps with naming>EnumNaming.
  EnumWrapping:
    active: true
    autoCorrect: true
    indentSize: 2
  Filename:
    active: false # Overlaps with naming>MatchingDeclarationName.
  FinalNewline:
    active: true
    autoCorrect: true
    insertFinalNewLine: true
  FunKeywordSpacing:
    active: true
    autoCorrect: true
  FunctionName: # Overlaps with naming>FunctionNaming.
    active: false
  FunctionReturnTypeSpacing:
    active: true
    autoCorrect: true
    maxLineLength: 120
  FunctionSignature:
    active: false
  FunctionStartOfBodySpacing:
    active: true
    autoCorrect: true
  FunctionTypeReferenceSpacing:
    active: true
    autoCorrect: true
  IfElseBracing:
    active: true
    autoCorrect: true
    indentSize: 2
  IfElseWrapping:
    active: true
    autoCorrect: true
    indentSize: 2
  ImportOrdering:
    active: true
    autoCorrect: true
    layout: '*,^'
  Indentation:
    active: true
    autoCorrect: true
    indentSize: 2
  KdocWrapping:
    active: true
    autoCorrect: true
    indentSize: 2
  MaximumLineLength:
    active: true
    maxLineLength: 120
    ignoreBackTickedIdentifier: false
  ModifierListSpacing:
    active: true
    autoCorrect: true
  ModifierOrdering:
    active: true
    autoCorrect: true
  MultiLineIfElse:
    active: true
    indentSize: 2
  MultilineExpressionWrapping:
    active: false
  NoBlankLineBeforeRbrace:
    active: true
    autoCorrect: true
  NoBlankLineInList:
    active: true
  NoBlankLinesInChainedMethodCalls:
    active: true
    autoCorrect: true
  NoConsecutiveBlankLines:
    active: true
    autoCorrect: true
  NoConsecutiveComments:
    active: true
  NoEmptyClassBody:
    active: true
    autoCorrect: true
  NoEmptyFirstLineInClassBody:
    active: true
    autoCorrect: true
    indentSize: 2
  NoEmptyFirstLineInMethodBlock:
    active: true
    autoCorrect: true
  NoLineBreakAfterElse:
    active: true
    autoCorrect: true
  NoLineBreakBeforeAssignment:
    active: true
    autoCorrect: true
  NoMultipleSpaces:
    active: true
    autoCorrect: true
  NoSemicolons:
    active: true
    autoCorrect: true
  NoSingleLineBlockComment:
    active: true
    autoCorrect: true
    indentSize: 2
  NoTrailingSpaces:
    active: true
    autoCorrect: true
  NoUnitReturn:
    active: true
    autoCorrect: true
  NoUnusedImports:
    active: true
    autoCorrect: true
  NoWildcardImports:
    active: false # Overlaps with style>WildcardImport.
  NullableTypeSpacing:
    active: true
    autoCorrect: true
  PackageName:
    active: true
  ParameterListSpacing:
    active: true
    autoCorrect: true
  ParameterListWrapping:
    active: true
    autoCorrect: true
    maxLineLength: 120
    indentSize: 2
  ParameterWrapping:
    active: true
    autoCorrect: true
    maxLineLength: 120
    indentSize: 2
  PropertyName:
    active: false
  PropertyWrapping:
    active: true
    autoCorrect: true
    maxLineLength: 120
    indentSize: 2
  SpacingAroundAngleBrackets:
    active: true
    autoCorrect: true
  SpacingAroundColon:
    active: true
    autoCorrect: true
  SpacingAroundComma:
    active: true
    autoCorrect: true
  SpacingAroundCurly:
    active: true
    autoCorrect: true
  SpacingAroundDot:
    active: true
    autoCorrect: true
  SpacingAroundDoubleColon:
    active: true
    autoCorrect: true
  SpacingAroundKeyword:
    active: true
    autoCorrect: true
  SpacingAroundOperators:
    active: true
    autoCorrect: true
  SpacingAroundParens:
    active: true
    autoCorrect: true
  SpacingAroundRangeOperator:
    active: true
    autoCorrect: true
  SpacingAroundUnaryOperator:
    active: true
    autoCorrect: true
  SpacingBetweenDeclarationsWithAnnotations:
    active: false
  SpacingBetweenDeclarationsWithComments:
    active: false
  SpacingBetweenFunctionNameAndOpeningParenthesis:
    active: true
    autoCorrect: true
  StringTemplate:
    active: true
    autoCorrect: true
  StringTemplateIndent:
    active: false
  TrailingCommaOnCallSite:
    active: true
    autoCorrect: true
    useTrailingCommaOnCallSite: true
  TrailingCommaOnDeclarationSite:
    active: true
    autoCorrect: true
    useTrailingCommaOnDeclarationSite: true
  TryCatchFinallySpacing:
    active: true
    autoCorrect: true
    indentSize: 2
  TypeArgumentListSpacing:
    active: true
    autoCorrect: true
    indentSize: 2
  TypeParameterListSpacing:
    active: true
    autoCorrect: true
    indentSize: 2
  UnnecessaryParenthesesBeforeTrailingLambda:
    active: true
    autoCorrect: true
  Wrapping:
    active: true
    autoCorrect: true
    indentSize: 2
    maxLineLength: 120

naming:
  BooleanPropertyNaming:
    active: false # Prefixing booleans isn't always useful.
  ClassNaming:
    active: true
    classPattern: '([A-Z][a-z0-9]+|A|I|KClass)+'
  ConstructorParameterNaming:
    active: true
    parameterPattern: '[a-z][A-Za-z0-9]*'
    privateParameterPattern: '[a-z][A-Za-z0-9]*'
  EnumNaming:
    active: true
    enumEntryPattern: '([A-Z][a-z0-9]+)+'
  ForbiddenClassName:
    active: false
  FunctionMaxLength:
    active: true
    maximumFunctionNameLength: 60
  FunctionMinLength:
    active: true
    minimumFunctionNameLength: 2
  FunctionNaming:
    active: true
    functionPattern: '[a-z][A-Za-z0-9]*'
    excludes:
      - '**/src/test/kotlin/**/*Test.kt'
  FunctionParameterNaming:
    active: true
    parameterPattern: '[a-z][A-Za-z0-9]*'
  InvalidPackageDeclaration:
    active: true
    rootPackage: 'kairo'
    requireRootInDeclaration: true
  LambdaParameterNaming:
    active: true
    parameterPattern: '[a-z][A-Za-z0-9]*|_'
  MatchingDeclarationName:
    active: true
    mustBeFirst: false
  MemberNameEqualsClassName:
    active: false
  NoNameShadowing:
    active: true
  NonBooleanPropertyPrefixedWithIs:
    active: true
  ObjectPropertyNaming:
    active: true
    constantPattern: '[a-z][A-Za-z0-9]*'
    propertyPattern: '[a-z][A-Za-z0-9]*'
    privatePropertyPattern: '[a-z][A-Za-z0-9]*'
  PackageNaming:
    active: true
    packagePattern: '[a-z][A-Za-z0-9]*(\.[a-z][A-Za-z0-9]*)*'
  TopLevelPropertyNaming:
    active: true
    constantPattern: '[a-z][A-Za-z0-9]*'
    propertyPattern: '[a-z][A-Za-z0-9]*'
    privatePropertyPattern: '[a-z][A-Za-z0-9]*'
  VariableMaxLength:
    active: false
  VariableMinLength:
    active: true
    minimumVariableNameLength: 1
  VariableNaming:
    active: true
    variablePattern: '[a-z][A-Za-z0-9]*'
    privateVariablePattern: '[a-z][A-Za-z0-9]*'

performance:
  ArrayPrimitive:
    active: true
  CouldBeSequence:
    active: true
  ForEachOnRange:
    active: true
  SpreadOperator:
    active: true
  UnnecessaryPartOfBinaryExpression:
    active: true
  UnnecessaryTemporaryInstantiation:
    active: true

potential-bugs:
  AvoidReferentialEquality:
    active: true
  CastNullableToNonNullableType:
    active: false # This rule has poor support for platform types.
  CastToNullableType:
    active: false
  Deprecation:
    active: true
  DontDowncastCollectionTypes:
    active: true
  DoubleMutabilityForCollection:
    active: true
  ElseCaseInsteadOfExhaustiveWhen:
    active: true
  EqualsAlwaysReturnsTrueOrFalse:
    active: true
  EqualsWithHashCodeExist:
    active: true
  ExitOutsideMain:
    active: true
  ExplicitGarbageCollectionCall:
    active: true
  HasPlatformType:
    active: true
  IgnoredReturnValue:
    active: false
  ImplicitDefaultLocale:
    active: true
  ImplicitUnitReturnType:
    active: true
    allowExplicitReturnType: true
  InvalidRange:
    active: true
  IteratorHasNextCallsNextMethod:
    active: true
  IteratorNotThrowingNoSuchElementException:
    active: true
  LateinitUsage:
    active: true
    ignoreAnnotated:
      - 'com.google.inject.Inject'
  MapGetWithNotNullAssertionOperator:
    active: true
  MissingPackageDeclaration:
    active: true
  NullCheckOnMutableProperty:
    active: true
  NullableToStringCall:
    active: false
  PropertyUsedBeforeDeclaration:
    active: true
  UnconditionalJumpStatementInLoop:
    active: true
  UnnecessaryNotNullCheck:
    active: true
  UnnecessaryNotNullOperator:
    active: true
  UnnecessarySafeCall:
    active: true
  UnreachableCatchBlock:
    active: true
  UnreachableCode:
    active: true
  UnsafeCallOnNullableType:
    active: false # checkNotNull and requireNotNull are often preferable, but leaving this open.
  UnsafeCast:
    active: true
  UnusedUnaryOperator:
    active: true
  UselessPostfixExpression:
    active: true
  WrongEqualsTypeParameter:
    active: true

style:
  AlsoCouldBeApply:
    active: false
  BracesOnIfStatements:
    active: true
    singleLine: 'never'
    multiLine: 'always'
  BracesOnWhenStatements:
    active: true
    singleLine: 'necessary'
    multiLine: 'consistent'
  CanBeNonNullable:
    active: true
  CascadingCallWrapping:
    active: true
    includeElvis: true
  ClassOrdering:
    active: true
  CollapsibleIfStatements:
    active: true
  DataClassContainsFunctions:
    active: false # Functions are OK in data classes.
  DataClassShouldBeImmutable:
    active: true
  DestructuringDeclarationWithTooManyEntries:
    active: true
    maxDestructuringEntries: 3
  DoubleNegativeLambda:
    active: true
  EqualsNullCall:
    active: true
  EqualsOnSignatureLine:
    active: true
  ExplicitCollectionElementAccessMethod:
    active: true
  ExplicitItLambdaParameter:
    active: true
  ExpressionBodySyntax:
    active: true
    includeLineWrapping: true
  ForbiddenAnnotation:
    active: true
  ForbiddenComment:
    active: false
  ForbiddenImport:
    active: true
    # Keep these in sync with IntelliJ auto-import exclusions (codeInsightSettings.xml).
    imports:
      - 'com.apple.eawt.*'
      - 'com.google.cloud.secretmanager.v1beta1.*'
      - 'com.google.cloud.secretmanager.v1beta2.*'
      - 'com.google.common.collect.Table'
      - 'com.sun.jdi.*'
      - 'com.sun.security.*'
      - 'com.sun.tools.javac.*'
      - 'io.kotest.core.spec.*'
      - 'io.kotest.core.test.TestScope'
      - 'java.awt.*'
      - 'java.beans.*'
      - 'java.io.ObjectInputFilter.Config'
      - 'java.nio.channels.*'
      - 'java.time.*'
      - 'java.util.Base64.*'
      - 'java.util.UUID'
      - 'java.util.concurrent.CancellationException'
      - 'java.util.concurrent.CountDownLatch'
      - 'java.util.concurrent.CyclicBarrier'
      - 'java.util.concurrent.Flow'
      - 'java.util.concurrent.atomic.*'
      - 'java.util.logging.LogManager'
      - 'java.xml.*'
      - 'javax.xml.*'
      - 'jdk.internal.*'
      - 'jdk.javadoc.*'
      - 'jdk.jfr.*'
      - 'kotlin.coroutines.cancellation.*'
      - 'kotlinx.coroutines.time.*'
      - 'kotlinx.datetime.Clock'
      - 'org.apache.logging.log4j.core.jmx.*'
      - 'org.intellij.lang.annotations.Flow'
      - 'org.koin.core.annotation.Singleton'
      - 'org.koin.core.component.*'
      - 'org.koin.core.context.GlobalContext.*'
      - 'org.koin.java.*'
      - 'org.koin.mp.*'
      - 'org.testcontainers.shaded.*'
      - 'org.w3c.dom.*'
      - 'sun.awt.*'
      - 'sun.net.*'
      - 'sun.nio.*'
      - 'sun.rmi.*'
      - 'sun.security.*'
  ForbiddenMethodCall:
    active: true
    methods:
      - 'java.lang.Runtime.getRuntime'
      - 'java.lang.System.currentTimeMillis'
      - 'java.lang.System.getenv'
      - 'java.lang.Thread.currentThread'
      - 'kotlin.io.print'
      - 'kotlin.io.println'
  ForbiddenSuppress:
    active: false
  ForbiddenVoid:
    active: true
    ignoreOverridden: false
    ignoreUsageInGenerics: false
  FunctionOnlyReturningConstant:
    active: false # This is sometimes useful for forward-compatibility.
  LoopWithTooManyJumpStatements:
    active: true
    maxJumpCount: 1
  MagicNumber:
    active: false # Magic numbers are often code smells, but leaving this open.
  MandatoryBracesLoops:
    active: true
  MaxChainedCallsOnSameLine:
    active: false
  MaxLineLength:
    active: false # Overlaps with formatting>MaximumLineLength.
  MayBeConst:
    active: true
  ModifierOrder:
    active: false # Overlaps with formatting>ModifierOrdering.
  MultilineLambdaItParameter:
    active: true
  MultilineRawStringIndentation:
    active: true
    indentSize: 2
  NestedClassesVisibility:
    active: true
  NewLineAtEndOfFile:
    active: false # Overlaps with formatting>FinalNewline.
  NoTabs:
    active: true
  NullableBooleanCheck:
    active: true
  ObjectLiteralToLambda:
    active: true
  OptionalAbstractKeyword:
    active: true
  OptionalUnit:
    active: false
  PreferToOverPairSyntax:
    active: false # The pair syntax is often clearer.
  ProtectedMemberInFinalClass:
    active: true
  RedundantExplicitType:
    active: true
  RedundantHigherOrderMapUsage:
    active: true
  RedundantVisibilityModifierRule:
    active: false # Conflicts with [explicitApi].
  ReturnCount:
    active: false
  SafeCast:
    active: true
  SerialVersionUIDInSerializableClass:
    active: true
  SpacingBetweenPackageAndImports:
    active: true
  StringShouldBeRawString:
    active: false
  ThrowsCount:
    active: false
  TrailingWhitespace:
    active: true
  TrimMultilineRawString:
    active: true
  UnderscoresInNumericLiterals:
    active: true
    acceptableLength: 4
    allowNonStandardGrouping: false
  UnnecessaryAbstractClass:
    active: false
  UnnecessaryAnnotationUseSiteTarget:
    active: true
  UnnecessaryApply:
    active: true
  UnnecessaryBackticks:
    active: true
  UnnecessaryBracesAroundTrailingLambda:
    active: true
  UnnecessaryFilter:
    active: true
  UnnecessaryInheritance:
    active: true
  UnnecessaryInnerClass:
    active: true
  UnnecessaryLet:
    active: false
  UnnecessaryParentheses:
    active: true
    allowForUnclearPrecedence: false
  UntilInsteadOfRangeTo:
    active: true
  UnusedImports:
    active: false # Overlaps with formatting>NoUnusedImports.
  UnusedParameter:
    active: true
  UnusedPrivateClass:
    active: true
  UnusedPrivateMember:
    active: true
  UnusedPrivateProperty:
    active: true
  UseAnyOrNoneInsteadOfFind:
    active: true
  UseArrayLiteralsInAnnotations:
    active: true
  UseCheckNotNull:
    active: true
  UseCheckOrError:
    active: false
  UseDataClass:
    active: true
    allowVars: false
  UseEmptyCounterpart:
    active: true
  UseIfEmptyOrIfBlank:
    active: true
  UseIfInsteadOfWhen:
    active: false
  UseIsNullOrEmpty:
    active: true
  UseLet:
    active: true
  UseOrEmpty:
    active: true
  UseRequire:
    active: false
  UseRequireNotNull:
    active: true
  UseSumOfInsteadOfFlatMapSize:
    active: true
  UselessCallOnNotNull:
    active: true
  UtilityClassWithPublicConstructor:
    active: true
  VarCouldBeVal:
    active: true
    ignoreLateinitVar: true
  WildcardImport:
    active: true
    excludeImports: []
