export const env = {
  LIMBER_API_BASE_URL: process.env.REACT_APP_LIMBER_API_BASE_URL!,
  LIMBER_GRAPHQL_BASE_URL: process.env.REACT_APP_LIMBER_GRAPHQL_BASE_URL!,
  AUTH0_DOMAIN: process.env.REACT_APP_AUTH0_DOMAIN!,
  COPYRIGHT_HOLDER: process.env.REACT_APP_COPYRIGHT_HOLDER!,
};
